# -*- coding: UTF-8 -*-
from rich import print

from client import Client






if __name__ == '__main__':

    text = 'Traffic incident detection plays a key role in intelligent transportation systems, which has gained great attention in transport engineering. In the past, traditional machine learning (ML) based detection methods achieved good performance under a centralised computing paradigm, where all data are transmitted to a central server for building ML models therein. Nowadays, deep neural networks based federated learning (FL) has become a mainstream detection approach to enable the model training in a decentralised manner while warranting local data governance. Such neural networks-centred techniques, however, have overshadowed the utility of well-established ML-based detection methods. In this work, we aim to explore the potential of potent conventional ML-based detection models in modern traffic scenarios featured by distributed data. We leverage an elegant but less explored distributed optimisation framework named Network Lasso, with guaranteed global convergence for convex problem formulations, integrate the potent convex ML model with it, and compare it with centralised learning, local learning, and federated learning methods atop a well-known traffic incident detection dataset. Experimental results show that the proposed network lasso-based approach provides a promising alternative to the FL-based approach in data-decentralised traffic scenarios, with a strong convergence guarantee while rekindling the significance of conventional ML-based detection methods.'
    text1 = 'In this paper, we extend the classical notion of d-increasing edited text function: some necessary and sufficient conditions concerning the d-increasingness property are provided, along with a characterization theorem based upon a differential criterion which is shown to be very useful for constructing new families of d-copulas. Several examples are presented. (c) 2021 Elsevier B.V. All rights reserved.'
    text2 = 'In this paper, two indirect adaptive control schemes for a class of multi-input-multi-output nonlinear singularly perturbed systems with partially unknown models and parameters are presented. Firstly, the original system dynamic equation is reformulated into a new form with identity control gain matrices, and a new multi-time-scale singularity-free neural network is employed to represent the new dynamic equation. Subsequently, an online identification scheme is proposed to update neural network weights where a set of auxiliary weight error vectors are used such that better convergence property can be achieved. Based on identification results, a singularity-free singular perturbation controller is developed to control the unknown nonlinear system. By using the singularity-free neural network and singular perturbation technique, the complexity in controller design for a singularly perturbed system is reduced, and the potential singularity problem is avoided. Moreover, a singularity-free dynamic surface control scheme is also proposed, and the “explosion of complexity” issue is relieved. Compared to conventional direct adaptive dynamic surface control schemes which use gradient-like updating laws and tracking errors to train the neural networks, the singularity-free dynamic surface controller is designed indirectly and the neural networks are updated using the identification errors. Therefore, better identification and control performance is achieved, and the potential singularity problem is also circumvented. The stability of the closed-loop system is rigorously proved via the Lyapunov approach, and the effectiveness of proposed identification and control schemes is demonstrated by simulations.'
    text3 = 'Inshore ship detection becomes challenging in high-resolution optical remote sensing image (RSI) because inshore ships are often incomplete and deformed due to the poor imaging condition and shadow of ship superstructure, and there are various interferences in harbor. A contour refinement and the improved generalized Hough transform (GHT)-based inshore ship detection scheme is proposed for RSI with complex harbor scenes. First, the suspected region of ships (SRS) is located in the entire RSI according to the line segments of ship body and docks. The contours in each SRS are then refined to repair the damaged ship head contour (SHC) using the convex set characteristics of ship head and subsequently reduce non-SHC by curvature filtering. In each refined SRS, equal frequency quantification instead of equal width quantification for R-Table construction and Gini coefficient-based decision criterion combining the number and distribution of votes are proposed to improve GHT (i.e., EG-GHT) and to extract SHCs as candidate targets. The false candidates are removed according to pixel proportion described by the structured binarization feature. Applying the border scoring strategy, the best candidates with the largest score among all the overlapped bounding boxes are selected as the final detection targets. Using the public RSIs with various cases, including turbid water, cloud occlusion, ships moored together, and ships with the different sizes, experimental results demonstrate the proposed scheme outperforms state-of-the-art contour-based methods and deep learning-based methods in terms of precision–recall rate and average precision, respectively.'
    client = Client()
    response = client.extract([text, text1, text2, text3])
    print(response)